// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Barrio
{
    public int IdBarrio { get; set; }

    public string NomBarrio { get; set; }

    public int? IdLocalidad { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();

    public virtual Localidade IdLocalidadNavigation { get; set; }
}