// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Butaca
{
    public int IdButaca { get; set; }

    public int? Numero { get; set; }

    public string Fila { get; set; }

    public int? IdSala { get; set; }

    public bool? Estado { get; set; }

    public virtual Sala Sala { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}