// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string NomCliente { get; set; }

    public string ApeCliente { get; set; }

    public int? IdTipoDoc { get; set; }

    public int? NumDoc { get; set; }

    public DateOnly? FechaNac { get; set; }

    public int? IdSexo { get; set; }

    public int? IdBarrio { get; set; }

    public string Domicilio { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Barrio IdBarrioNavigation { get; set; }

    public virtual Sexo IdSexoNavigation { get; set; }

    public virtual TiposDocumento IdTipoDocNavigation { get; set; }

    public virtual ICollection<Reserva> Reservas { get; set; } = new List<Reserva>();
}