// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class DetalleFactura
{
    public int IdDetalleFactura { get; set; }

    public int? NumFactura { get; set; }

    public int? NumTicket { get; set; }

    public int? Cantidad { get; set; }

    public decimal? Precio { get; set; }

    public virtual Factura NumFacturaNavigation { get; set; }

    public virtual Ticket NumTicketNavigation { get; set; }
}