// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Funciones
{
    public int IdFuncion { get; set; }

    public int? IdPelicula { get; set; }

    public int? IdSala { get; set; }

    public DateOnly? FechaFuncion { get; set; }

    public TimeOnly? HoraFuncion { get; set; }

    public virtual Pelicula Pelicula { get; set; }

    public virtual Sala Sala { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}