// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public DateOnly? Fecha { get; set; }

    public int? IdCliente { get; set; }

    public int? IdEstadoReserva { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual EstadosReserva IdEstadoReservaNavigation { get; set; }

    public virtual ICollection<Ticket> Tickets { get; set; } = new List<Ticket>();
}