// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Sala
{
    public int IdSala { get; set; }

    public string NombreSala { get; set; }

    public int? Capacidad { get; set; }

    public int? IdTipoSala { get; set; }

    public virtual ICollection<Butaca> Butacas { get; set; } = new List<Butaca>();

    public virtual ICollection<Funciones> Funciones { get; set; } = new List<Funciones>();

    public virtual TiposSala IdTipoSalaNavigation { get; set; }
}