// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Sexo
{
    public int IdSexo { get; set; }

    public string Sexo1 { get; set; }

    public virtual ICollection<Cliente> Clientes { get; set; } = new List<Cliente>();
}