// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class Ticket
{
    public int NumTicket { get; set; }

    public int? IdFuncion { get; set; }

    public int? IdButaca { get; set; }

    public int? IdReserva { get; set; }

    public decimal? Precio { get; set; }

    public DateOnly? Fecha { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();

    public virtual Butaca Butaca { get; set; }

    public virtual Funciones Funciones { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }
}