// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class TiposContacto
{
    public int IdTipoContacto { get; set; }

    public string TipoContacto { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();
}