// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cine_Tp.Data;

public partial class TiposCompra
{
    public int IdTipoCompra { get; set; }

    public string TipoCompra { get; set; }

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
}